# fly.toml app configuration file generated for green-earth on 2023-08-04T23:37:27-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "green-earth"
primary_region = "gru"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[deploy]
   release_command = "python manage.py migrate --noinput"
