# Generated by Django 4.2.4 on 2023-08-17 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help', models.CharField(choices=[('EA', 'Educação ambiental'), ('LAN', 'Limpeza e preservação de áreas naturais'), ('R', 'Reflorestamento e plantio de árvores'), ('RE', 'Reciclagem'), ('ER', 'Energias renováveis'), ('AS', 'Agricultura sustentável'), ('CA', 'Conservação da água'), ('MS', 'Mobilidade sustentável'), ('GR', 'Gestão de resíduos'), ('PVS', 'Proteção da vida selvagem'), ('AEP', 'Advocacia e engajamento político'), ('TS', 'Tecnologias sustentáveis'), ('ACL', 'Ações em comunidades locais'), ('MA', 'Monitoramento ambiental'), ('DC', 'Design e comunicação')], max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Volunteers',
            },
        ),
        migrations.CreateModel(
            name='NewMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('concluded', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('volunteers', models.ManyToManyField(blank=True, null=True, to='volunteers.volunteers')),
            ],
            options={
                'verbose_name_plural': 'NewMission',
            },
        ),
        migrations.CreateModel(
            name='HistoryVoluntary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='volunteers.newmission')),
                ('voluntary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='volunteers.volunteers')),
            ],
            options={
                'verbose_name_plural': 'HistoryVoluntary',
            },
        ),
    ]
