# Generated by Django 4.2.4 on 2023-08-06 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='crimedenunciations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_denunciations'),
        ),
        migrations.AlterField(
            model_name='crimedenunciations',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimedenunciations',
            name='reference_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='NewMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('volunteers', models.ManyToManyField(to='volunteers.volunteers')),
            ],
            options={
                'verbose_name_plural': 'NewMission',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='volunteers',
            field=models.ManyToManyField(to='blog.newmission'),
        ),
    ]
