# Generated by Django 4.2.4 on 2023-08-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
        ('blog', '0002_blogpost_update_alter_crimedenunciations_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newmission',
            name='concluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='volunteers',
            field=models.ManyToManyField(blank=True, null=True, to='blog.newmission'),
        ),
        migrations.AlterField(
            model_name='newmission',
            name='volunteers',
            field=models.ManyToManyField(blank=True, null=True, to='volunteers.volunteers'),
        ),
    ]
