# Generated by Django 4.2.4 on 2023-08-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_genders_alter_users_gender_delete_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genders',
            name='gender',
            field=models.CharField(choices=[('F', 'Femenine'), ('M', 'Masculine')], max_length=1),
        ),
    ]
