# Generated by Django 4.2.4 on 2023-08-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(default='Financial', max_length=10),
        ),
    ]
