# Generated by Django 4.2.4 on 2023-08-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0002_alter_contributors_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionhistory',
            name='company',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
