# Generated by Django 4.2.4 on 2023-08-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0003_contributionhistory_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionhistory',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
