# Generated by Django 4.2.4 on 2023-08-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0004_alter_contributionhistory_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionhistory',
            name='value',
            field=models.IntegerField(),
        ),
    ]
